window.clientSeed = [
  {
    "code": "1532",
    "name": "C. A. NUNES FAUSTINO SUPERMERCADO",
    "suspended": false,
    "inactive": false,
    "legacyOrder": 46168,
    "cep": "11462-000",
    "street": "Rua Dona Joana de Menezes Faro",
    "number": "747",
    "neighborhood": "Sítio Paecara (Vicente de Carv",
    "city": "Guarujá"
  },
  {
    "code": "1601",
    "name": "SUPERMERCADO NOVO JAN LTDA",
    "suspended": false,
    "inactive": false,
    "legacyOrder": 46166,
    "cep": "11714-190",
    "street": "Rua José Veríssimo",
    "number": "400",
    "neighborhood": "Balneário Japura",
    "city": "Praia Grande"
  },
  {
    "code": "3012",
    "name": "QUATRO AMIGOS COMERCIO VAREJISTA DE HORTIFRUTI LTDA",
    "suspended": false,
    "inactive": false,
    "legacyOrder": 46164,
    "cep": "11088-180",
    "street": "Avenida VEREADOR ALVARO GUIMARAES",
    "number": "114",
    "neighborhood": "RADIO CLUB",
    "city": "Santos"
  },
  {
    "code": "1598",
    "name": "SUPERMERCADO NOVA ESMERALDA DE PRAIA GRANDE LTDA",
    "suspended": false,
    "inactive": false,
    "legacyOrder": 46164,
    "cep": "11713-300",
    "street": "Avenida Zélia Gigliolli Galves",
    "number": "2",
    "neighborhood": "Balneário Esmeralda",
    "city": "Praia Grande"
  },
  {
    "code": "1529",
    "name": "ATALAIA COMERCIO ATACADISTA DE PRODUTOS ALIMENTICIOS LTDA",
    "suspended": false,
    "inactive": false,
    "legacyOrder": 46163,
    "cep": "11330-690",
    "street": "Rua Odair Muller de Azevedo Marques",
    "number": "141",
    "neighborhood": "Vila Margarida",
    "city": "São Vicente"
  },
  {
    "code": "1530",
    "name": "ATALAIA COMERCIO ATACADISTA DE PRODUTOS ALIMENTICIOS LTDA",
    "suspended": false,
    "inactive": false,
    "legacyOrder": 46163,
    "cep": "11347-520",
    "street": "Avenida Quarentenário",
    "number": "310",
    "neighborhood": "Jardim Quarentenário",
    "city": "São Vicente"
  },
  {
    "code": "3182",
    "name": "MERCADO PRIMO'S LTDA",
    "suspended": false,
    "inactive": false,
    "legacyOrder": 46163,
    "cep": "11325-030",
    "street": "Rua Aviador Edu Chaves",
    "number": "320",
    "neighborhood": "Jardim Recanto São Vicente",
    "city": "São Vicente"
  },
  {
    "code": "1595",
    "name": "SUPERMERCADO IRMAOS COSTA LTDA",
    "suspended": false,
    "inactive": false,
    "legacyOrder": 46163,
    "cep": "11713-160",
    "street": "Rua Itibere da Cunha",
    "number": "159",
    "neighborhood": "Parque das Américas",
    "city": "Praia Grande"
  },
  {
    "code": "1596",
    "name": "SUPERMERCADO IRMAOS COSTA LTDA",
    "suspended": false,
    "inactive": false,
    "legacyOrder": 46163,
    "cep": "11310-180",
    "street": "Rua Marquês de São Vicente - até 471/472",
    "number": "65",
    "neighborhood": "Centro",
    "city": "São Vicente"
  },
  {
    "code": "2977",
    "name": "TENNESSEE CUBATAO LTDA",
    "suspended": false,
    "inactive": false,
    "legacyOrder": 46163,
    "cep": "11520-000",
    "street": "Avenida Nove de Abril - de 2833/2834 ao fim",
    "number": "2345",
    "neighborhood": "Vila Nova",
    "city": "Cubatão"
  },
  {
    "code": "1544",
    "name": "CASA LUANDA SUPERMERCADOS LTDA",
    "suspended": false,
    "inactive": false,
    "legacyOrder": 46162,
    "cep": "11390-001",
    "street": "Avenida Antônio Emmerick - até 619 - lado ímpar",
    "number": "335",
    "neighborhood": "Vila Cascatinha",
    "city": "São Vicente"
  },
  {
    "code": "1546",
    "name": "CENTER BOI NELORE COMERCIO DE CARNES LTDA",
    "suspended": false,
    "inactive": false,
    "legacyOrder": 46162,
    "cep": "11310-400",
    "street": "Rua Quinze de Novembro",
    "number": "289",
    "neighborhood": "Centro",
    "city": "São Vicente"
  },
  {
    "code": "1603",
    "name": "SUPERMERCADO TALISMA DA VILA LTDA",
    "suspended": false,
    "inactive": false,
    "legacyOrder": 46162,
    "cep": "11330-580",
    "street": "Rua Monte Belvedere",
    "number": "610",
    "neighborhood": "Vila Margarida",
    "city": "São Vicente"
  },
  {
    "code": "1604",
    "name": "SUPERMERCADO TALISMA DE SAO VICENTE LTDA",
    "suspended": false,
    "inactive": false,
    "legacyOrder": 46162,
    "cep": "11330-300",
    "street": "Avenida das Nações Unidas",
    "number": "865",
    "neighborhood": "Vila Margarida",
    "city": "São Vicente"
  },
  {
    "code": "1607",
    "name": "TENNESSEE LITORAL COMERCIO DE CARNES LTDA",
    "suspended": false,
    "inactive": false,
    "legacyOrder": 46161,
    "cep": "11704-100",
    "street": "Avenida Presidente Kennedy",
    "number": "7469",
    "neighborhood": "Cidade Ocian",
    "city": "Praia Grande"
  },
  {
    "code": "1590",
    "name": "SAO JOSE DE CAICARA SUPERMERCADO E PADARIA LTDA",
    "suspended": false,
    "inactive": false,
    "legacyOrder": 46157,
    "cep": "11707-000",
    "street": "Avenida Presidente Kennedy",
    "number": "11155",
    "neighborhood": "Vila Caiçara",
    "city": "Praia Grande"
  },
  {
    "code": "1525",
    "name": "ANDRADE COMERCIO DE PRODUTOS ALIMENTICIOS LTDA",
    "suspended": false,
    "inactive": false,
    "legacyOrder": 46156,
    "cep": "11462-300",
    "street": "Rua Júlio Pedro Pontes",
    "number": "207",
    "neighborhood": "Jardim Monteiro da Cruz (Vicen",
    "city": "Guarujá"
  },
  {
    "code": "1534",
    "name": "C. A. NUNES FAUSTINO SUPERMERCADO",
    "suspended": false,
    "inactive": false,
    "legacyOrder": 46156,
    "cep": "11451-000",
    "street": "Avenida Presidente Vargas",
    "number": "883",
    "neighborhood": "Parque Estuário (Vicente de Ca",
    "city": "Guarujá"
  },
  {
    "code": "2757",
    "name": "CENTRAL DE CARNES BOI NELORE SV LTDA",
    "suspended": false,
    "inactive": false,
    "legacyOrder": 46156,
    "cep": "11370-001",
    "street": "Avenida ANTONIO EMMERICK",
    "number": "1481",
    "neighborhood": "JARDIM GUASSU",
    "city": "São Vicente"
  },
  {
    "code": "1571",
    "name": "L. B. HORTIFRUTIGRANJEIROS LTDA",
    "suspended": false,
    "inactive": false,
    "legacyOrder": 46156,
    "cep": "11045-001",
    "street": "Avenida Conselheiro Nébias - de 383 a 531 - lado ímpar",
    "number": "501",
    "neighborhood": "Encruzilhada",
    "city": "Santos"
  },
  {
    "code": "1572",
    "name": "LELO CARNES LTDA",
    "suspended": false,
    "inactive": false,
    "legacyOrder": 46156,
    "cep": "11707-110",
    "street": "Rua Vitório Morbim",
    "number": "630",
    "neighborhood": "Vilamar",
    "city": "Praia Grande"
  },
  {
    "code": "1587",
    "name": "REDE BOI NOBRE DE CARNES LTDA",
    "suspended": false,
    "inactive": false,
    "legacyOrder": 46156,
    "cep": "11717-110",
    "street": "Avenida Júlio Prestes de Albuquerque",
    "number": "475",
    "neighborhood": "Vila Mirim",
    "city": "Praia Grande"
  },
  {
    "code": "1599",
    "name": "SUPERMERCADO NOVA ONDA LTDA",
    "suspended": false,
    "inactive": false,
    "legacyOrder": 46156,
    "cep": "11717-110",
    "street": "Avenida Júlio Prestes de Albuquerque",
    "number": "400",
    "neighborhood": "Vila Mirim",
    "city": "Praia Grande"
  },
  {
    "code": "1609",
    "name": "TENNESSEE LITORAL COMERCIO DE CARNES LTDA",
    "suspended": false,
    "inactive": false,
    "legacyOrder": 46156,
    "cep": "11085-202",
    "street": "Avenida Nossa Senhora de Fátima ",
    "number": "816",
    "neighborhood": "Chico de Paula",
    "city": "Santos"
  },
  {
    "code": "1551",
    "name": "CHRISTIANE SANTOS REIS 33036801839",
    "suspended": false,
    "inactive": false,
    "legacyOrder": 46155,
    "cep": "11712-590",
    "street": "Rua dos Eucaliptos",
    "number": "262",
    "neighborhood": "Jardim Samambaia",
    "city": "Praia Grande"
  },
  {
    "code": "1555",
    "name": "CLEIDE CRISTINA TEIXEIRA MACEDO-SAO VICENTE",
    "suspended": false,
    "inactive": false,
    "legacyOrder": 46155,
    "cep": "11355-000",
    "street": "Rua MARECHAL HUMBERTO DE ALENCAR CASTELO BRANCO",
    "number": "732",
    "neighborhood": "CIDADE NAUTICA",
    "city": "São Vicente"
  },
  {
    "code": "1583",
    "name": "REDE BOI NOBRE DE CARNES LTDA",
    "suspended": false,
    "inactive": false,
    "legacyOrder": 46155,
    "cep": "11714-040",
    "street": "Rua Clodoardo Amaral",
    "number": "694",
    "neighborhood": "Balneário Japura",
    "city": "Praia Grande"
  },
  {
    "code": "1536",
    "name": "C.M- COMERCIO VAREJISTA DE HORTIFRUTIGRANJEIROS LTDA.",
    "suspended": false,
    "inactive": false,
    "legacyOrder": 46154,
    "cep": "11701-120",
    "street": "Rua Oswaldo de Oliveira",
    "number": "82",
    "neighborhood": "Boqueirão",
    "city": "Praia Grande"
  },
  {
    "code": "1582",
    "name": "REDE BOI NOBRE DE CARNES LTDA",
    "suspended": false,
    "inactive": false,
    "legacyOrder": 46154,
    "cep": "11713-160",
    "street": "Rua Itibere da Cunha",
    "number": "138",
    "neighborhood": "Parque das Américas",
    "city": "Praia Grande"
  },
  {
    "code": "1584",
    "name": "REDE BOI NOBRE DE CARNES LTDA",
    "suspended": false,
    "inactive": false,
    "legacyOrder": 46154,
    "cep": "11703-200",
    "street": "Avenida Presidente Kennedy",
    "number": "5420",
    "neighborhood": "Campo da Aviação",
    "city": "Praia Grande"
  },
  {
    "code": "1519",
    "name": "58.866.491 IVANIZE ALVES DE BARROS",
    "suspended": false,
    "inactive": false,
    "legacyOrder": 46150,
    "cep": "11330-675",
    "street": "Rua Particular Hum",
    "number": "137",
    "neighborhood": "Vila Margarida",
    "city": "São Vicente"
  },
  {
    "code": "1509",
    "name": "43.359.573 LEIDIANE DE CARVALHO PROVENCI",
    "suspended": false,
    "inactive": false,
    "legacyOrder": 46149,
    "cep": "11704-440",
    "street": "Rua Kikusaburo Tanaca",
    "number": "98",
    "neighborhood": "Cidade Ocian",
    "city": "Praia Grande"
  },
  {
    "code": "1521",
    "name": "A.B.T. CID - MINI MERCADO, LANCHONETE E COMERCIO VAREJISTA DE BEBIDAS",
    "suspended": false,
    "inactive": false,
    "legacyOrder": 46149,
    "cep": "11355-030",
    "street": "Rua Tambaú",
    "number": "1445",
    "neighborhood": "Vila Nossa Senhora de Fátima",
    "city": "São Vicente"
  },
  {
    "code": "1573",
    "name": "MARQUES & SANTOS COMERCIO DE ALIMENTOS LTDA",
    "suspended": false,
    "inactive": false,
    "legacyOrder": 46149,
    "cep": "11370-400",
    "street": "Avenida PENEDO",
    "number": "85",
    "neighborhood": "CATIAPOA",
    "city": "São Vicente"
  },
  {
    "code": "1577",
    "name": "MINI MERCADO ESPAGUETE LTDA",
    "suspended": false,
    "inactive": false,
    "legacyOrder": 46149,
    "cep": "11725-410",
    "street": "Rua Professor Olavo Paula Borges",
    "number": "45",
    "neighborhood": "Tude Bastos (Sítio do Campo)",
    "city": "Praia Grande"
  },
  {
    "code": "1578",
    "name": "OLIGUI COMERCIO DE PRODUTOS ALIMENTICIOS LTDA",
    "suspended": false,
    "inactive": false,
    "legacyOrder": 46149,
    "cep": "11700-450",
    "street": "Rua Cínthia Giufrida",
    "number": "306",
    "neighborhood": "Canto do Forte",
    "city": "Praia Grande"
  },
  {
    "code": "1579",
    "name": "PANIFICADORA POMPEIA LIMITADA",
    "suspended": false,
    "inactive": false,
    "legacyOrder": 46149,
    "cep": "11725-320",
    "street": "Avenida Irmãos Adornos",
    "number": "449",
    "neighborhood": "Tude Bastos (Sítio do Campo)",
    "city": "Praia Grande"
  },
  {
    "code": "1591",
    "name": "SUPERMERCADO FIGUEROA LTDA",
    "suspended": false,
    "inactive": false,
    "legacyOrder": 46149,
    "cep": "11700-400",
    "street": "Avenida Marechal Mallet",
    "number": "532",
    "neighborhood": "Canto do Forte",
    "city": "Praia Grande"
  },
  {
    "code": "1605",
    "name": "SUPERMERCADO XIXOVA LTDA",
    "suspended": false,
    "inactive": false,
    "legacyOrder": 46149,
    "cep": "11700-450",
    "street": "Rua Cínthia Giufrida",
    "number": "852",
    "neighborhood": "Canto do Forte",
    "city": "Praia Grande"
  },
  {
    "code": "1515",
    "name": "53.185.274 MARCOS PAULO DE SANTANA CONCEICAO",
    "suspended": false,
    "inactive": false,
    "legacyOrder": 46147,
    "cep": "11704-520",
    "street": "Rua Carlos Vanderlinde",
    "number": "90",
    "neighborhood": "Vila Mirim",
    "city": "Praia Grande"
  },
  {
    "code": "3112",
    "name": "BRILHANTE SUPERMERCADO LTDA",
    "suspended": false,
    "inactive": false,
    "legacyOrder": 46147,
    "cep": "11520-000",
    "street": "Avenida Nove de Abril - de 2833/2834 ao fim",
    "number": "3400",
    "neighborhood": "Vila Nova",
    "city": "Cubatão"
  },
  {
    "code": "1539",
    "name": "CACAUCENTER COMERCIO DE GENEROS ALIMENTICIOS LTDA",
    "suspended": false,
    "inactive": false,
    "legacyOrder": 46147,
    "cep": "11380-000",
    "street": "Avenida Prefeito José Monteiro - lado par",
    "number": "744",
    "neighborhood": "Jardim Independência",
    "city": "São Vicente"
  },
  {
    "code": "1585",
    "name": "REDE BOI NOBRE DE CARNES LTDA",
    "suspended": false,
    "inactive": false,
    "legacyOrder": 46147,
    "cep": "11708-207",
    "street": "Avenida PRESIDENTE KENNEDY",
    "number": "10451",
    "neighborhood": "MARACANA",
    "city": "Praia Grande"
  },
  {
    "code": "1608",
    "name": "TENNESSEE LITORAL COMERCIO DE CARNES LTDA",
    "suspended": false,
    "inactive": false,
    "legacyOrder": 46147,
    "cep": "11702-200",
    "street": "Avenida Presidente Kennedy",
    "number": "2514",
    "neighborhood": "Vila Guilhermina",
    "city": "Praia Grande"
  },
  {
    "code": "3206",
    "name": "42.555.866 CASSIANO RODRIGUES",
    "suspended": false,
    "inactive": false,
    "legacyOrder": 46146,
    "cep": "11347-210",
    "street": "Rua Luiz Ferreira Morgado",
    "number": "264",
    "neighborhood": "Jardim Rio Branco",
    "city": "São Vicente"
  },
  {
    "code": "1586",
    "name": "REDE BOI NOBRE DE CARNES LTDA",
    "suspended": false,
    "inactive": false,
    "legacyOrder": 46142,
    "cep": "11702-200",
    "street": "Avenida Presidente Kennedy",
    "number": "5116",
    "neighborhood": "Vila Guilhermina",
    "city": "Praia Grande"
  },
  {
    "code": "3059",
    "name": "DANILO DE SANTANA BEZERRA",
    "suspended": false,
    "inactive": false,
    "legacyOrder": 46140,
    "cep": "11436-095",
    "street": "Avenida Dois",
    "number": "190",
    "neighborhood": "Vila Zilda",
    "city": "Guarujá"
  },
  {
    "code": "1610",
    "name": "ULISSES ALVES DOMINGUES CIA LTDA",
    "suspended": false,
    "inactive": false,
    "legacyOrder": 46140,
    "cep": "11310-400",
    "street": "Rua Quinze de Novembro",
    "number": "537",
    "neighborhood": "Centro",
    "city": "São Vicente"
  },
  {
    "code": "1549",
    "name": "CENTRAL DE CARNES JP LTDA",
    "suspended": false,
    "inactive": false,
    "legacyOrder": 46139,
    "cep": "11707-000",
    "street": "Avenida Presidente Kennedy",
    "number": "12718",
    "neighborhood": "Vila Caiçara",
    "city": "Praia Grande"
  },
  {
    "code": "1588",
    "name": "REDE MAGALO SUPERMERCADO LTDA",
    "suspended": false,
    "inactive": false,
    "legacyOrder": 46139,
    "cep": "11713-090",
    "street": "Avenida José Leandro de Carvalho",
    "number": "1850",
    "neighborhood": "Parque das Américas",
    "city": "Praia Grande"
  },
  {
    "code": "1602",
    "name": "SUPERMERCADO PIRAMIDE LTDA",
    "suspended": false,
    "inactive": false,
    "legacyOrder": 46135,
    "cep": "11330-130",
    "street": "Rua Cornélio Pires",
    "number": "129",
    "neighborhood": "Parque Bitaru",
    "city": "São Vicente"
  },
  {
    "code": "1560",
    "name": "FORMOSA PRIME - CARNES E ROTISSERIE LTDA",
    "suspended": false,
    "inactive": false,
    "legacyOrder": 46129,
    "cep": "11701-380",
    "street": "Avenida São Paulo",
    "number": "1078",
    "neighborhood": "Boqueirão",
    "city": "Praia Grande"
  },
  {
    "code": "3187",
    "name": "60.130.690 EDUARDA AGUIAR DE ALMEIDA",
    "suspended": false,
    "inactive": false,
    "legacyOrder": 46128,
    "cep": "11700-190",
    "street": "Rua Espírito Santo",
    "number": "336",
    "neighborhood": "Canto do Forte",
    "city": "Praia Grande"
  },
  {
    "code": "3186",
    "name": "PANIFICADORA WALT DISNEY DE SAO VICENTE LTDA",
    "suspended": false,
    "inactive": false,
    "legacyOrder": 46128,
    "cep": "11355-190",
    "street": "Rua Alferes Germano da Costa",
    "number": "288",
    "neighborhood": "Cidade Naútica",
    "city": "São Vicente"
  },
  {
    "code": "1600",
    "name": "SUPERMERCADO NOVO JAN 2 LTDA",
    "suspended": false,
    "inactive": false,
    "legacyOrder": 46126,
    "cep": "11718-330",
    "street": "Rua Ruy Manoel Sampaio Seabra Pereira",
    "number": "200",
    "neighborhood": "Jardim Quietude",
    "city": "Praia Grande"
  },
  {
    "code": "1526",
    "name": "ANTONIO MIRAMOTO & FILHO LTDA",
    "suspended": false,
    "inactive": false,
    "legacyOrder": 46111,
    "cep": "11360-260",
    "street": "Praça Matteo Bei",
    "number": "93",
    "neighborhood": "Vila Jockei Clube",
    "city": "São Vicente"
  },
  {
    "code": "351",
    "name": "RENAN COLAÃ‡O DA SILVA",
    "suspended": false,
    "inactive": false,
    "legacyOrder": 46111,
    "cep": "11706-150",
    "street": "Rua Santo Agostinho",
    "number": "105",
    "neighborhood": "Vila Caiçara",
    "city": "Praia Grande"
  },
  {
    "code": "1570",
    "name": "JOAO DOS SANTOS 56017766520",
    "suspended": false,
    "inactive": true,
    "legacyOrder": 46107,
    "cep": "11714-440",
    "street": "Avenida Rocha Pita",
    "number": "444",
    "neighborhood": "Jardim Trevo",
    "city": "Praia Grande"
  },
  {
    "code": "1589",
    "name": "RENATO GUALCHI",
    "suspended": false,
    "inactive": true,
    "legacyOrder": 46107,
    "cep": "11702-060",
    "street": "Rua Honduras",
    "number": "195",
    "neighborhood": "Vila Guilhermina",
    "city": "Praia Grande"
  },
  {
    "code": "1575",
    "name": "MERCADO DAS CARNES CARVALHO LTDA",
    "suspended": false,
    "inactive": true,
    "legacyOrder": 46101,
    "cep": "11070-102",
    "street": "Rua Doutor Carvalho de Mendonça - de 425/426 a 609/610",
    "number": "487",
    "neighborhood": "Vila Belmiro",
    "city": "Santos"
  },
  {
    "code": "1508",
    "name": "31.740.008 REGINA DE PAULA AMBROSIO",
    "suspended": false,
    "inactive": true,
    "legacyOrder": 46086,
    "cep": "11705-580",
    "street": "Avenida Ã‚ngelo Perino",
    "number": "75",
    "neighborhood": "Balneário Maracanã",
    "city": "Praia Grande"
  },
  {
    "code": "1558",
    "name": "DANAUTICA COMERCIO DE CARNES LTDA",
    "suspended": false,
    "inactive": true,
    "legacyOrder": 46077,
    "cep": "11355-400",
    "street": "Avenida Manoel de Abreu",
    "number": "464",
    "neighborhood": "Cidade Naútica",
    "city": "São Vicente"
  },
  {
    "code": "2767",
    "name": "LOJAO DO GG LTDA",
    "suspended": false,
    "inactive": true,
    "legacyOrder": 46077,
    "cep": "11365-030",
    "street": "Rua Armando Vitório Bei",
    "number": "271",
    "neighborhood": "Parque São Vicente",
    "city": "São Vicente"
  },
  {
    "code": "1593",
    "name": "SUPERMERCADO GALEGO LTDA",
    "suspended": false,
    "inactive": true,
    "legacyOrder": 46076,
    "cep": "11340-000",
    "street": "Rua Frei Gaspar - de 1403/1404 a 3101/3102",
    "number": "1858",
    "neighborhood": "Parque São Vicente",
    "city": "São Vicente"
  },
  {
    "code": "1592",
    "name": "SUPERMERCADO GALEGO LTDA",
    "suspended": false,
    "inactive": true,
    "legacyOrder": 46065,
    "cep": "11520-000",
    "street": "Avenida Nove de Abril - de 2833/2834 ao fim",
    "number": "3400",
    "neighborhood": "Vila Nova",
    "city": "Cubatão"
  },
  {
    "code": "1513",
    "name": "51.947.871 LETICIA MELO CAMPELO",
    "suspended": false,
    "inactive": false,
    "legacyOrder": null,
    "cep": "11730-000",
    "street": "Rua RUA DOS MARINHEIROS",
    "number": "713",
    "neighborhood": "BALNEARIO ANCHIETA",
    "city": "Mongaguá"
  },
  {
    "code": "1517",
    "name": "53.428.293 LIVIA OLAH DE AQUINO MASSEO",
    "suspended": false,
    "inactive": false,
    "legacyOrder": null,
    "cep": "11700-005",
    "street": "Avenida Presidente Costa e Silva - lado par",
    "number": "224",
    "neighborhood": "Boqueirão",
    "city": "Praia Grande"
  },
  {
    "code": "1523",
    "name": "ADEILTON & CLAUDIANA MINIMERCADO LTDA",
    "suspended": false,
    "inactive": false,
    "legacyOrder": null,
    "cep": "11717-130",
    "street": "Rua Martiniano José das Neves",
    "number": "32520",
    "neighborhood": "Vila Mirim",
    "city": "Praia Grande"
  },
  {
    "code": "1606",
    "name": "CENTER CARNES E ROTISSERIE MURITIBA LTDA",
    "suspended": false,
    "inactive": false,
    "legacyOrder": null,
    "cep": "08340-460",
    "street": "Rua Manuel Veloso da Costa",
    "number": "38",
    "neighborhood": "Jardim Vila Carrão",
    "city": "São Paulo"
  },
  {
    "code": "1569",
    "name": "GABRIELA DE MELO SILVA 43983678882",
    "suspended": false,
    "inactive": false,
    "legacyOrder": null,
    "cep": "11451-240",
    "street": "Rua São Paulo Valão",
    "number": "145",
    "neighborhood": "Sítio Paecara (Vicente de Carv",
    "city": "Guarujá"
  },
  {
    "code": "1574",
    "name": "MERCADAO DE CARNES E MERCEARIA SAO VICENTE LTDA",
    "suspended": false,
    "inactive": false,
    "legacyOrder": null,
    "cep": "11370-001",
    "street": "Avenida ANTONIO EMMERICK",
    "number": "827",
    "neighborhood": "JARDIM GUASSU",
    "city": "São Vicente"
  },
  {
    "code": "1576",
    "name": "MERCADO E HORTIFRUTI DAVILLA LTDA",
    "suspended": false,
    "inactive": false,
    "legacyOrder": null,
    "cep": "11706-110",
    "street": "Rua AVENIDA MIAMI",
    "number": "689",
    "neighborhood": "CAICARA",
    "city": "Praia Grande"
  },
  {
    "code": "2724",
    "name": "MERCADO PARQUE PRAIA GRANDE LTDA",
    "suspended": false,
    "inactive": false,
    "legacyOrder": null,
    "cep": "11713-295",
    "street": "Avenida Jose Leandro de Carvalho",
    "number": "1850",
    "neighborhood": "Esmeralda",
    "city": "Praia Grande"
  },
  {
    "code": "1581",
    "name": "RALPH GONCALVES CORLETO",
    "suspended": false,
    "inactive": false,
    "legacyOrder": null,
    "cep": "11712-540",
    "street": "Rua das Seringueiras",
    "number": "116",
    "neighborhood": "Jardim Samambaia",
    "city": "Praia Grande"
  },
  {
    "code": "1594",
    "name": "SUPERMERCADO GALEGO LTDA",
    "suspended": false,
    "inactive": false,
    "legacyOrder": null,
    "cep": "11380-000",
    "street": "Avenida Prefeito José Monteiro - lado par",
    "number": "914",
    "neighborhood": "Jardim Independência",
    "city": "São Vicente"
  },
  {
    "code": "1597",
    "name": "SUPERMERCADO LITANE LTDA",
    "suspended": false,
    "inactive": false,
    "legacyOrder": null,
    "cep": "11365-030",
    "street": "Rua Armando Vitório Bei",
    "number": "271",
    "neighborhood": "Parque São Vicente",
    "city": "São Vicente"
  }
];
